Add API Cloud Deploy

diff --git a/deployment/build-and-stage.yaml b/deployment/build-and-stage.yaml
--- a/deployment/build-and-stage.yaml
+++ b/deployment/build-and-stage.yaml
@@ -27,23 +27,23 @@ steps:
 - name: gcr.io/cloud-builders/gcloud
   entrypoint: bash
   args:
-    - '-c'
-    - |
-      read current_build _ <<< $(gcloud builds list --filter=tags="build-and-stage" --format="value(id,create_time)" --sort-by=create_time --ongoing)
+  - '-c'
+  - |
+    read current_build _ <<< $(gcloud builds list --filter=tags="build-and-stage" --format="value(id,create_time)" --sort-by=create_time --ongoing)
+    if [[ -z "${current_build}" ]]; then
+      echo "Could not find any matching builds."
+      exit 1
+    fi
+    while [[ "${current_build}" != "${BUILD_ID}" ]]; do
+      echo "Waiting for build ${current_build}"
+      sleep 30
+      read current_build _ <<< $(gcloud builds list --filter=tags="build-and-stage" --format="value(id,create_time)" --sort-by=create_time  --ongoing)
       if [[ -z "${current_build}" ]]; then
         echo "Could not find any matching builds."
-        exit 1
+        exit 1;
       fi
-      while [[ "${current_build}" != "${BUILD_ID}" ]]; do
-        echo "Waiting for build ${current_build}"
-        sleep 30
-        read current_build _ <<< $(gcloud builds list --filter=tags="build-and-stage" --format="value(id,create_time)" --sort-by=create_time  --ongoing)
-        if [[ -z "${current_build}" ]]; then
-          echo "Could not find any matching builds."
-          exit 1;
-        fi
-      done
-      echo "Finished waiting for other builds."
+    done
+    echo "Finished waiting for other builds."
   id: 'cloud-build-queue'
   waitFor: ['-']
 
@@ -156,7 +156,13 @@ steps:
   ]
   dir: deployment/clouddeploy/gke-workers
 
-  # TODO(michaelkedar): API Backend
+# API Backend
+- name: 'gcr.io/cloud-builders/gcloud'
+  args: ['deploy', 'releases', 'create', 'osv-$SHORT_SHA', '--project=oss-vdb', '--region=us-central1',
+    '--delivery-pipeline=osv-api', '--images',
+    "osv-server=gcr.io/oss-vdb/osv-server:$COMMIT_SHA"
+  ]
+  dir: deployment/clouddeploy/osv-api
 
 timeout: 7200s
 # Also set in Cloud Build:
@@ -168,11 +174,11 @@ options:
 tags: ['build-and-stage']
 
 images:
-  - 'gcr.io/oss-vdb/worker-base:$COMMIT_SHA'
-  - 'gcr.io/oss-vdb/worker:$COMMIT_SHA'
-  - 'gcr.io/oss-vdb/importer:$COMMIT_SHA'
-  - 'gcr.io/oss-vdb/exporter:$COMMIT_SHA'
-  - 'gcr.io/oss-vdb/alpine-cve-convert:$COMMIT_SHA'
-  - 'gcr.io/oss-vdb/combine-to-osv:$COMMIT_SHA'
-  - 'gcr.io/oss-vdb/debian-convert:$COMMIT_SHA'
-  - 'gcr.io/oss-vdb/osv-server:$COMMIT_SHA'
+- 'gcr.io/oss-vdb/worker-base:$COMMIT_SHA'
+- 'gcr.io/oss-vdb/worker:$COMMIT_SHA'
+- 'gcr.io/oss-vdb/importer:$COMMIT_SHA'
+- 'gcr.io/oss-vdb/exporter:$COMMIT_SHA'
+- 'gcr.io/oss-vdb/alpine-cve-convert:$COMMIT_SHA'
+- 'gcr.io/oss-vdb/combine-to-osv:$COMMIT_SHA'
+- 'gcr.io/oss-vdb/debian-convert:$COMMIT_SHA'
+- 'gcr.io/oss-vdb/osv-server:$COMMIT_SHA'
